import { Header, Menu } from '@components'
import './globals.css'

import { Poppins } from 'next/font/google'

const popins = Poppins({
	weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
	subsets: ['latin'],
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	return (
		<html lang='en'>
			<body
				className={`${popins.className} flex h-screen w-screen bg-plantation overflow-hidden`}>
				<Menu />
				<div className='m-6 ml-0 p-16 bg-white rounded-3xl w-full overflow-y-scroll overflow-x-hidden'>
					<Header />
					{children}
				</div>
			</body>
		</html>
	)
}
